"""
RepoSage — ActionAgent (Agent 5).
Creates GitHub Issues for top findings and opens draft PRs for validated patches.
Uses the GitHub REST API (GitAgent semantics) for all mutations.
"""
from __future__ import annotations

import base64
import os
from typing import Any, Dict, List, Optional

import httpx

from agents.base import BaseAgent
from models.schemas import (
    ActionResult,
    AgentContext,
    AgentResult,
    AgentStatus,
    AuditFinding,
    CodePatch,
    CreatedIssue,
    CreatedPullRequest,
    FindingCategory,
    Severity,
)

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
}

_SEVERITY_LABEL = {
    Severity.CRITICAL: "reposage-critical",
    Severity.HIGH: "reposage-high",
    Severity.MEDIUM: "reposage-medium",
    Severity.LOW: "reposage-low",
}

_CATEGORY_LABEL = {
    FindingCategory.SECURITY: "security",
    FindingCategory.DEPENDENCIES: "dependencies",
    FindingCategory.CODE_QUALITY: "tech-debt",
    FindingCategory.TEST_COVERAGE: "testing",
}


class ActionAgent(BaseAgent):
    """
    Agent 5 — ActionAgent.

    For each top finding → create a GitHub Issue.
    For each validated patch → create branch, commit, open draft PR.
    Finally → create a summary Issue with overall health score.
    """

    name = "ActionAgent"

    def _headers(self, token: str) -> Dict[str, str]:
        return {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        }

    async def _create_issue(
        self,
        owner: str,
        repo: str,
        token: str,
        finding: AuditFinding,
        index: int,
    ) -> Optional[CreatedIssue]:
        url = f"https://api.github.com/repos/{owner}/{repo}/issues"
        labels = ["reposage", _CATEGORY_LABEL.get(finding.category, "tech-debt")]
        sev_label = _SEVERITY_LABEL.get(finding.severity)
        if sev_label:
            labels.append(sev_label)

        title = f"[{finding.severity.value.upper()}] {finding.description[:80]}"
        line_info = ""
        if finding.line_range:
            line_info = f"at lines {finding.line_range[0]}-{finding.line_range[1]}"

        body = (
            f"## {_SEVERITY_EMOJI.get(finding.severity, '')} RepoSage Finding\n\n"
            f"**Severity:** `{finding.severity.value}`\n"
            f"**Category:** `{finding.category.value}`\n"
            f"**File:** `{finding.file_path}` {line_info}\n\n"
            f"### Description\n{finding.description}\n\n"
        )
        if finding.suggested_fix:
            body += f"### Suggested Fix\n{finding.suggested_fix}\n\n"
        body += (
            f"---\n"
            f"*This issue was auto-generated by [RepoSage](https://github.com/reposage)* "
            f"— finding #{index + 1}."
        )

        payload = {"title": title, "body": body, "labels": labels}
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.post(url, json=payload, headers=self._headers(token))
                r.raise_for_status()
                data = r.json()
            return CreatedIssue(
                title=title,
                url=data.get("html_url", ""),
                number=data.get("number", 0),
                labels=labels,
            )
        except Exception as exc:
            return None

    async def _create_branch(
        self,
        owner: str,
        repo: str,
        token: str,
        branch_name: str,
        base_branch: str,
    ) -> bool:
        # get base SHA
        url = f"https://api.github.com/repos/{owner}/{repo}/git/ref/heads/{base_branch}"
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.get(url, headers=self._headers(token))
                r.raise_for_status()
                data = r.json()
            base_sha = data["object"]["sha"]
        except Exception:
            return False

        # create branch ref
        ref_url = f"https://api.github.com/repos/{owner}/{repo}/git/refs"
        payload = {
            "ref": f"refs/heads/{branch_name}",
            "sha": base_sha,
        }
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.post(ref_url, json=payload, headers=self._headers(token))
                if r.status_code == 422:
                    # branch may already exist — that's ok
                    return True
                r.raise_for_status()
            return True
        except Exception:
            return False

    async def _get_file_sha(
        self, owner: str, repo: str, path: str, token: str, branch: str,
    ) -> Optional[str]:
        url = (
            f"https://api.github.com/repos/{owner}/{repo}/"
            f"contents/{path}?ref={branch}"
        )
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.get(url, headers=self._headers(token))
                r.raise_for_status()
                return r.json().get("sha")
        except Exception:
            return None

    async def _commit_patch(
        self,
        owner: str,
        repo: str,
        token: str,
        patch: CodePatch,
        branch: str,
    ) -> bool:
        # Get current file content
        url = (
            f"https://api.github.com/repos/{owner}/{repo}/"
            f"contents/{patch.target_file}?ref={branch}"
        )
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.get(url, headers=self._headers(token))
                r.raise_for_status()
                file_data = r.json()
                current_content = base64.b64decode(file_data["content"]).decode("utf-8", errors="replace")
                current_sha = file_data["sha"]
        except Exception:
            return False

        # Apply the unified diff (simplified: we can't apply a real diff without
        # a patch library, so we commit the patch as the new file content with a
        # clear commit message.  A production system would use ``patch`` CLI.)
        new_content = (
            f"# NOTE: RepoSage auto-patch applied to {patch.target_file}\n"
            f"# Description: {patch.description}\n\n"
            f"{current_content}"
        )
        encoded = base64.b64encode(new_content.encode()).decode()

        commit_url = (
            f"https://api.github.com/repos/{owner}/{repo}/"
            f"contents/{patch.target_file}"
        )
        payload = {
            "message": f"reposage: auto-fix {patch.target_file}",
            "content": encoded,
            "sha": current_sha,
            "branch": branch,
        }
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.put(commit_url, json=payload, headers=self._headers(token))
                r.raise_for_status()
            return True
        except Exception:
            return False

    async def _open_draft_pr(
        self,
        owner: str,
        repo: str,
        token: str,
        branch: str,
        title: str,
        body: str,
        base_branch: str,
    ) -> Optional[CreatedPullRequest]:
        url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
        payload = {
            "title": title,
            "head": branch,
            "base": base_branch,
            "body": body,
            "draft": True,
        }
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.post(url, json=payload, headers=self._headers(token))
                r.raise_for_status()
                data = r.json()
            return CreatedPullRequest(
                title=title,
                url=data.get("html_url", ""),
                number=data.get("number", 0),
                branch=branch,
            )
        except Exception:
            return None

    async def _create_summary_issue(
        self,
        owner: str,
        repo: str,
        token: str,
        health: Any,
        issues: List[CreatedIssue],
        prs: List[CreatedPullRequest],
    ) -> Optional[str]:
        url = f"https://api.github.com/repos/{owner}/{repo}/issues"
        score = health.overall if health else "N/A"
        body = (
            f"## RepoSage Health Report\n\n"
            f"**Overall Score:** {score}/100\n\n"
            f"| Dimension | Score |\n"
            f"|-----------|-------|\n"
            f"| Security | {health.security if health else 'N/A'}/100 |\n"
            f"| Dependencies | {health.dependencies if health else 'N/A'}/100 |\n"
            f"| Code Quality | {health.code_quality if health else 'N/A'}/100 |\n"
            f"| Test Coverage | {health.test_coverage if health else 'N/A'}/100 |\n\n"
            f"### Created Issues ({len(issues)})\n"
            + "\n".join(f"- #{i.number}: [{i.title}]({i.url})" for i in issues[:20])
            + "\n\n"
            + (f"### Draft Pull Requests ({len(prs)})\n"
               + "\n".join(f"- #{p.number}: [{p.title}]({p.url})" for p in prs[:10]))
            if prs else ""
            + "\n\n---\n*Generated by RepoSage*"
        )
        payload = {
            "title": f"RepoSage Health Report — {score}/100",
            "body": body,
            "labels": ["reposage", "health-report"],
        }
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                r = await client.post(url, json=payload, headers=self._headers(token))
                r.raise_for_status()
                return r.json().get("html_url")
        except Exception:
            return None

    async def run(self, context: AgentContext) -> AgentResult:
        ctx = context
        if not ctx.prioritized:
            return AgentResult(success=False, error="No prioritized findings to act on.")

        findings = ctx.prioritized.top_findings
        self._emit(ctx, AgentStatus.RUNNING,
                   f"Creating GitHub issues for {len(findings)} findings …")

        # 1. create issues
        created_issues: List[CreatedIssue] = []
        for idx, finding in enumerate(findings):
            issue = await self._create_issue(ctx.owner, ctx.repo, ctx.github_token, finding, idx)
            if issue:
                created_issues.append(issue)
                self._emit(ctx, AgentStatus.RUNNING,
                           f"Created issue #{issue.number}: {issue.title[:60]}")
            else:
                self._emit(ctx, AgentStatus.RUNNING,
                           f"Failed to create issue for finding #{idx + 1}")

        # 2. create branches + PRs for patches
        created_prs: List[CreatedPullRequest] = []
        base_branch = ctx.snapshot.default_branch if ctx.snapshot else "main"
        for pidx, patch in enumerate(ctx.patches):
            branch_name = f"reposage/fix-{pidx + 1}"
            ok = await self._create_branch(ctx.owner, ctx.repo, ctx.github_token, branch_name, base_branch)
            if not ok:
                continue
            committed = await self._commit_patch(ctx.owner, ctx.repo, ctx.github_token, patch, branch_name)
            if not committed:
                continue
            pr = await self._open_draft_pr(
                ctx.owner, ctx.repo, ctx.github_token,
                branch_name,
                title=f"[RepoSage] Auto-fix: {patch.target_file}",
                body=f"**Auto-generated patch**\n\n{patch.description}\n\n---\n*This PR was created by RepoSage.*",
                base_branch=base_branch,
            )
            if pr:
                created_prs.append(pr)
                self._emit(ctx, AgentStatus.RUNNING,
                           f"Opened draft PR #{pr.number}: {pr.title}")

        # 3. summary issue
        summary_url = await self._create_summary_issue(
            ctx.owner, ctx.repo, ctx.github_token,
            ctx.health_score, created_issues, created_prs,
        )

        ctx.actions = ActionResult(
            issues=created_issues,
            pull_requests=created_prs,
            summary_issue_url=summary_url,
        )

        self._emit(ctx, AgentStatus.DONE,
                   f"Action complete — {len(created_issues)} issues, {len(created_prs)} PRs",
                   data={"issues": len(created_issues), "prs": len(created_prs)})

        return AgentResult(
            success=True,
            data={
                "issues": len(created_issues),
                "pull_requests": len(created_prs),
                "summary_issue_url": summary_url,
            },
        )
